# docker-compose.prod.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    command: ['--storageEngine=wiredTiger']
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
